"""add photo_filename to tests

Revision ID: 1d383f9ad68a
Revises: b8d97cdddd2d
Create Date: 2026-03-30 19:13:08.922355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d383f9ad68a'
down_revision = 'b8d97cdddd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###
