"""skywarn worksheet: storm header, damage passed_via, watch/condition/station tables

Revision ID: 52f6dae15d8b
Revises: 5ff4cbd95d1e
Create Date: 2026-07-08 16:15:16.847095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f6dae15d8b'
down_revision = '5ff4cbd95d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storm_net_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storm_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('time', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['storm_id'], ['storms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storm_net_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storm_net_conditions_storm_id'), ['storm_id'], unique=False)

    op.create_table('storm_net_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storm_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('station', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('time_in', sa.Text(), nullable=True),
    sa.Column('time_out', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['storm_id'], ['storms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storm_net_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storm_net_stations_storm_id'), ['storm_id'], unique=False)

    op.create_table('storm_watch_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storm_id', sa.Integer(), nullable=False),
    sa.Column('tsm_watch', sa.Boolean(), nullable=True),
    sa.Column('tsm_warning', sa.Boolean(), nullable=True),
    sa.Column('tdo_watch', sa.Boolean(), nullable=True),
    sa.Column('tdo_warning', sa.Boolean(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['storm_id'], ['storms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storm_watch_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storm_watch_warnings_storm_id'), ['storm_id'], unique=False)

    with op.batch_alter_table('damage_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passed_via', sa.Text(), nullable=True))

    with op.batch_alter_table('storms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_control_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('net_control_callsign', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('freq_main', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('freq_north', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('freq_south', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('freq_dtx', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storms', schema=None) as batch_op:
        batch_op.drop_column('freq_dtx')
        batch_op.drop_column('freq_south')
        batch_op.drop_column('freq_north')
        batch_op.drop_column('freq_main')
        batch_op.drop_column('net_control_callsign')
        batch_op.drop_column('net_control_name')

    with op.batch_alter_table('damage_reports', schema=None) as batch_op:
        batch_op.drop_column('passed_via')

    with op.batch_alter_table('storm_watch_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storm_watch_warnings_storm_id'))

    op.drop_table('storm_watch_warnings')
    with op.batch_alter_table('storm_net_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storm_net_stations_storm_id'))

    op.drop_table('storm_net_stations')
    with op.batch_alter_table('storm_net_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storm_net_conditions_storm_id'))

    op.drop_table('storm_net_conditions')
    # ### end Alembic commands ###
