"""storm center: storms and damage_reports

Revision ID: 5ff4cbd95d1e
Revises: a3f9b2c4d701
Create Date: 2026-07-01 12:19:15.983928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff4cbd95d1e'
down_revision = 'a3f9b2c4d701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('nws_event_type', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('center_coordinates', sa.Text(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storms_event_date'), ['event_date'], unique=False)

    op.create_table('damage_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storm_id', sa.Integer(), nullable=True),
    sa.Column('reporter_name', sa.Text(), nullable=False),
    sa.Column('reporter_member_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('damage_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('photo_filename', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['storm_id'], ['storms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('damage_reports', schema=None) as batch_op:
        batch_op.create_index('ix_damage_reports_storm_status', ['storm_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('damage_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_damage_reports_storm_status')

    op.drop_table('damage_reports')
    with op.batch_alter_table('storms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storms_event_date'))

    op.drop_table('storms')
    # ### end Alembic commands ###
