"""add coordinates to sirens

Revision ID: e31996b0ab7e
Revises: 1d383f9ad68a
Create Date: 2026-03-31 09:18:28.767183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31996b0ab7e'
down_revision = '1d383f9ad68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sirens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sirens', schema=None) as batch_op:
        batch_op.drop_column('coordinates')

    # ### end Alembic commands ###
