"""Add can_edit_sirens permission and siren maintenance log

Revision ID: e730cd1d99a4
Revises: c1a4e9d2f7b3
Create Date: 2026-04-09 12:07:33.663460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e730cd1d99a4'
down_revision = 'c1a4e9d2f7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siren_maintenance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siren_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['siren_id'], ['sirens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siren_maintenance_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siren_maintenance_log_siren_id'), ['siren_id'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_edit_sirens', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('can_edit_sirens')

    with op.batch_alter_table('siren_maintenance_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siren_maintenance_log_siren_id'))

    op.drop_table('siren_maintenance_log')
    # ### end Alembic commands ###
